[project]
name = "computer-use-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use[memory]>=0.1.47",
    "playwright>=1.52.0",
]
